const os=require('os');
// console.log(os.arch());
// const freemem=os.freemem();
// console.log(`${freemem/1024/1024/1024}`);
// const total=os.totalmem();
// console.log(`${total/1024/1024/1024}`);
console.log(os.hostname());
console.log(os.platform());
console.log(os.tmpdir());
console.log(os.type());
console.log(os.uptime());